<?php

namespace Tests\Feature;

use App\Models\Dealer;
use App\Models\DealerGroup;
use App\Models\User;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;

class DealerGroupControllerTest extends TestCase
{
    use RefreshDatabase, WithFaker;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->seed();
    }

    /**
     * A basic feature test example.
     *
     * @return void
     */
    public function auth_user()
    {
        $dealers = Dealer::factory()->count(10)->create();
        $user = User::factory()->create([
            'dealer_id' => 1
        ]);
        $this->actingAs($user);
        return $dealers;
    }

    public function test_store_dealerGroup()
    {
        $dealers =  $this->auth_user();

        $formData = [
            'name'          => $this->faker->country,
            'description'   => $this->faker->sentence(),
            'slug'          => $this->faker->unique()->slug,
            'status'        => $this->faker->boolean(),
        ];

        $response = $this->post('/api/v1/dealer/groups', $formData);
        $response->assertStatus(200);
        $response->dump();
    }

    public function test_update_dealerGRoup()
    {
        $dealers =  $this->auth_user();
        $group = DealerGroup::factory()->create();

        $formData = [
            'name'          => $this->faker->country . 'x',
            'description'   => $this->faker->sentence() . 'x',
            'slug'          => $this->faker->unique()->slug . 'x',
            'status'        => $this->faker->boolean(),
        ];

        $response = $this->put("/api/v1/dealer/groups/$group->id", $formData);
        $response->assertStatus(200);
        $response->dump();
    }
}
