<?php

namespace Tests\Feature;

use App\Models\Dealer;
use App\Models\DealerZone;
use App\Models\News;
use App\Models\User;
use Carbon\Carbon;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;

class ExampleTest extends TestCase
{

    use RefreshDatabase, WithFaker;
    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->seed();
    }
    /**
     * A basic test example.
     *
     * @return void
     */
    public function test_the_application_returns_a_successful_response()
    {

        $formData = [
            'name' => 'Jan Cruz',
            'email'  =>  'jan@email.com',
            'password'   => 'password',
            'password_confirmation' => 'password'
        ];

        $response = $this->post('/api/v1/auth/register', $formData);
        $response->assertStatus(200);
    }
}
