<?php

namespace Tests\Feature;

use App\Models\Dealer;
use App\Models\DealerGroup;
use App\Models\DealerZone;
use App\Models\ModelYear;
use App\Models\User;
use App\Models\Variant;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;

class ModelYearControllerTest extends TestCase
{
    use RefreshDatabase, WithFaker;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->seed();
    }
    /**
     * A basic feature test example.
     *
     * @return void
     */


    /**
     * A basic feature test example.
     *
     * @return void
     */

    public function auth_user()
    {
        $group   = DealerGroup::factory()->count(2)->create();
        $zones   = DealerZone::factory()->count(5)->create();

        $group->each(function ($item, $key) use ($zones) {
            $dealers =  Dealer::factory()->count(2)->create([
                'group_id' => $item->id,
                'zone_id'  => $zones[$key]->id
            ]);
            $variant = Variant::factory()->count(2)->create();
        });

        $user = User::factory()->create();
        $this->actingAs($user);
    }

    public function test_store_modelYear()
    {
        $this->auth_user();

        $form = [
            'name' => $this->faker->year(),
            'code' => $this->faker->countryCode(),
            'description' => $this->faker->sentence(),
            'status' => $this->faker->boolean()
        ];


        $response = $this->post('api/v1/model/years', $form);
        $response->dump();
        $response->assertStatus(200);

        $this->assertDatabaseHas('model_years', [
            'name'                  => $form['name'],
            'code'                  => $form['code'],
            'status'                => $form['status'],
            'description'           => $form['description'],
        ]);
    }

    public function test_update_modelYear()
    {
        $this->auth_user();

        $modelYear = ModelYear::create([
            'name' => $this->faker->year(),
            'code' => $this->faker->countryCode(),
            'description' => $this->faker->sentence(),
            'status' => $this->faker->boolean()
        ]);

        $form = [
            'name' => $this->faker->year() . 'updated',
            'code' => $this->faker->countryCode() . 'updated',
            'description' => $this->faker->sentence() . 'updated',
            'status' => $this->faker->boolean()
        ];


        $response = $this->put("api/v1/model/years/$modelYear->id", $form);
        $response->dump();
        $response->assertStatus(200);

        $this->assertDatabaseHas('model_years', [
            'name'                  => $form['name'],
            'code'                  => $form['code'],
            'status'                => $form['status'],
            'description'           => $form['description'],
        ]);
    }
}
